const baseSemesters=[
 {id:'Y1S1',label:'Year 1 Semester 1',session:'June 2025',status:'done',courses:[
  ['UBMM1011',"Sun Zi's Art of War and Business Strategies",1,'Free Module'],['UCCB1013','Fundamentals of Business Systems',3,'Core'],['UCCD1203','Database Development and Applications',3,'Core'],['UCCM2433','Fundamentals of Statistics',3,'Specialisation'],['UCCN1004','Data Communications and Networking',4,'Core'],['UCCT1013','Introduction to Information Systems Design',3,'Core']]},
 {id:'Y1S2',label:'Year 1 Semester 2',session:'October 2025',status:'done',courses:[
  ['MPU32143','English for Information Technology',3,'MPU'],['MPU33013','Malaysian Economy',3,'MPU'],['UCCT2153','Digital Supply Chain Management',3,'Field Elective']]},
 {id:'Y1S3',label:'Year 1 Semester 3',session:'February 2026',status:'done',courses:[
  ['MPU3182','Falsafah dan Isu Semasa',2,'MPU'],['UCCD1133','Introduction to Computer Organisation and Architecture',3,'Core'],['UCCD3013','E-Commerce Practices',3,'Specialisation'],['UCCN1223','Cybersecurity',3,'Core'],['UCCT1104','Application Programming',4,'Core'],['UCCT2103','Financial Technology',3,'Specialisation']]},
 {id:'Y2S1',label:'Year 2 Semester 1',session:'June 2026',status:'current',courses:[
  ['UCCB1223','Rapid Application Development',3,'Core'],['UCCB3133','Business Analytics',3,'Core'],['UCCD2323','Front-End Web Development',3,'Core'],['UCCD3253','Enterprise Systems',3,'Core'],['UCCT1113','Information Technology Infrastructure for Business',3,'Core'],['UBMM2013','Operations Management',3,'Free Module']]}
];
let currentCourse=null,db,currentCourseFilter="";
const customKey='utarHubCustomCourses',notesKey='utarHubNotes',tasksKey='utarHubTasks',themeKey='utarHubTheme';
const $=id=>document.getElementById(id);
function esc(s){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function toast(msg='Saved ✓'){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500)}
function customCourses(){try{return JSON.parse(localStorage.getItem(customKey)||'[]')}catch{return[]}}
function getTasks(){try{return JSON.parse(localStorage.getItem(tasksKey)||'[]')}catch{return[]}}
function saveTasks(arr){localStorage.setItem(tasksKey,JSON.stringify(arr))}
function allSemesters(){const custom=customCourses();return baseSemesters.map(s=>({...s,courses:[...s.courses,...custom.filter(c=>c.sem===s.id).map(c=>[c.code,c.name,c.credit,'Custom'])]}))}
function courseId(sem,code){return sem+'__'+code}
function courseInfoFromId(id){for(const s of allSemesters()){for(const c of s.courses){if(courseId(s.id,c[0])===id)return {sem:s.id,semLabel:s.label,code:c[0],name:c[1],credit:c[2],type:c[3],id}}}return {sem:'',semLabel:'',code:id.split('__')[1]||'',name:'Unknown course',id}}
function showTab(id){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.navbtn').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));if(id==='home')refreshDashboard();if(id==='filecenter')renderFileCenter()}
function setCourseFilter(v){currentCourseFilter=v||'';const sel=$('courseSemSelect');if(sel)sel.value=currentCourseFilter;document.querySelectorAll('.chip[data-semfilter]').forEach(x=>x.classList.toggle('active',x.dataset.semfilter===currentCourseFilter));renderCourses()}
function semesterHTML(s,compact=false){const total=s.courses.reduce((a,c)=>a+Number(c[2]),0);const wrap=document.createElement('div');wrap.className='semester '+(s.status==='current'?'current':'');wrap.innerHTML=`<div class="semhead"><div><h3>${s.label}</h3><div class="semdate">${s.session}</div></div><div style="display:flex;gap:5px;align-items:flex-start"><span class="statusbadge ${s.status}">${s.status==='done'?'Completed':'Current'}</span><span class="creditbadge">${total} cr</span></div></div>`;s.courses.forEach(c=>{const id=courseId(s.id,c[0]);const el=document.createElement('div');el.className='course';el.dataset.search=(c[0]+' '+c[1]).toLowerCase();el.dataset.id=id;el.innerHTML=`<div class="course-top"><span class="code">${esc(c[0])}</span><span class="credit">${c[2]} cr</span></div><div class="course-name">${esc(c[1])}</div><div class="pills"><span class="pill">${esc(c[3])}</span><span class="pill file" id="count-${cssSafe(id)}">0 files</span><span class="pill task" id="taskcount-${cssSafe(id)}">0 tasks</span></div>`;el.onclick=()=>openCourse({sem:s.id,code:c[0],name:c[1],credit:c[2],type:c[3],id});wrap.appendChild(el)});return wrap}
function renderCourses(){const grid=$('semesterGrid'),home=$('homeSemesterGrid');grid.innerHTML='';home.innerHTML='';const sems=allSemesters();const filtered=currentCourseFilter?sems.filter(s=>s.id===currentCourseFilter):sems;filtered.forEach(s=>grid.appendChild(semesterHTML(s)));sems.forEach(s=>home.appendChild(semesterHTML(s,true)));applySearch();refreshCounts();refreshDashboard()}
function cssSafe(s){return s.replace(/[^a-zA-Z0-9_-]/g,'_')}
function applySearch(){const q=$('searchBox').value.trim().toLowerCase();document.querySelectorAll('.course').forEach(el=>el.classList.toggle('hidden-search',q&&!el.dataset.search.includes(q)))}
$('searchBox').addEventListener('input',applySearch);
let noteTimer;$('courseNotes').addEventListener('input',()=>{if(!currentCourse)return;if($('noteSaveState'))$('noteSaveState').textContent='Saving...';clearTimeout(noteTimer);noteTimer=setTimeout(()=>saveNotes(true),650)});
function openCourse(c){currentCourse=c;$('drawerCode').textContent=c.code;$('drawerTitle').textContent=c.name;$('drawerMeta').textContent=`${c.sem} · ${c.credit} credits · ${c.type}`;const notes=JSON.parse(localStorage.getItem(notesKey)||'{}');$('courseNotes').value=notes[c.id]||'';if($('noteSaveState'))$('noteSaveState').textContent='Auto-save enabled';$('overlay').classList.add('show');$('drawer').classList.add('show');showDrawerTab('files');loadFiles(c.id);renderTasks(c.id)}
function closeDrawer(){$('overlay').classList.remove('show');$('drawer').classList.remove('show');currentCourse=null}
function showDrawerTab(id){document.querySelectorAll('.dpanel').forEach(x=>x.classList.remove('active'));$('d-'+id).classList.add('active');document.querySelectorAll('.dtab').forEach(x=>x.classList.toggle('active',x.dataset.dtab===id))}
function saveNotes(silent=false){if(!currentCourse)return;const notes=JSON.parse(localStorage.getItem(notesKey)||'{}');notes[currentCourse.id]=$('courseNotes').value;localStorage.setItem(notesKey,JSON.stringify(notes));if($('noteSaveState'))$('noteSaveState').textContent='Saved '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});if(!silent)toast('Notes saved ✓')}
function addTask(){if(!currentCourse)return;const title=$('taskTitle').value.trim(),due=$('taskDue').value;if(!title)return toast('Enter a task name');const arr=getTasks();arr.push({id:Date.now()+Math.random(),courseId:currentCourse.id,courseCode:currentCourse.code,courseName:currentCourse.name,title,due,done:false,created:Date.now()});saveTasks(arr);$('taskTitle').value='';$('taskDue').value='';renderTasks(currentCourse.id);refreshCounts();refreshDashboard();toast('Task added ✓')}
function renderTasks(cid){const arr=getTasks().filter(t=>t.courseId===cid).sort((a,b)=>(a.done-b.done)||((a.due||'9999').localeCompare(b.due||'9999'))),list=$('taskList');if(!arr.length){list.innerHTML='<div class="empty">No tasks yet.</div>';return}list.innerHTML='';arr.forEach(t=>{const row=document.createElement('div');row.className='taskrow '+(t.done?'done':'');row.innerHTML=`<input type="checkbox" ${t.done?'checked':''}><div><div class="tasktitle">${esc(t.title)}</div><div class="taskmeta">${t.due?'Due '+formatDate(t.due):'No due date'}</div></div><button class="mini">Delete</button>`;row.querySelector('input').onchange=e=>toggleTask(t.id,e.target.checked);row.querySelector('button').onclick=()=>deleteTask(t.id);list.appendChild(row)})}
function toggleTask(id,done){const arr=getTasks(),t=arr.find(x=>x.id===id);if(t)t.done=done;saveTasks(arr);if(currentCourse)renderTasks(currentCourse.id);refreshCounts();refreshDashboard()}
function deleteTask(id){saveTasks(getTasks().filter(x=>x.id!==id));if(currentCourse)renderTasks(currentCourse.id);refreshCounts();refreshDashboard()}
function formatDate(s){if(!s)return'';const d=new Date(s+'T00:00:00');return d.toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}
function openAddCourse(){$('addOverlay').classList.add('show');$('addDrawer').classList.add('show')}
function closeAddCourse(){$('addOverlay').classList.remove('show');$('addDrawer').classList.remove('show')}
function addCustomCourse(){const sem=$('newSem').value,code=$('newCode').value.trim().toUpperCase(),name=$('newName').value.trim(),credit=Number($('newCredit').value);if(!code||!name)return toast('Enter course code and name');const arr=customCourses();arr.push({sem,code,name,credit});localStorage.setItem(customKey,JSON.stringify(arr));closeAddCourse();$('newCode').value='';$('newName').value='';renderCourses();toast('Course added ✓')}
function initDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('UTARStudyHubDB',1);req.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains('files')){const store=d.createObjectStore('files',{keyPath:'id',autoIncrement:true});store.createIndex('courseId','courseId',{unique:false})}};req.onsuccess=e=>{db=e.target.result;resolve()};req.onerror=()=>reject(req.error)})}
function addFiles(files){if(!currentCourse||!files.length)return;const cat=$('fileCategory').value,tx=db.transaction('files','readwrite'),store=tx.objectStore('files');[...files].forEach(file=>store.add({courseId:currentCourse.id,name:file.name,type:file.type,size:file.size,category:cat,created:Date.now(),blob:file}));tx.oncomplete=()=>{loadFiles(currentCourse.id);refreshCounts();refreshDashboard();renderFileCenter();toast(`${files.length} file${files.length===1?'':'s'} saved ✓`)}}
function getFiles(cid){return new Promise(resolve=>{const tx=db.transaction('files','readonly'),idx=tx.objectStore('files').index('courseId'),req=idx.getAll(cid);req.onsuccess=()=>resolve(req.result||[])})}
function getAllFiles(){return new Promise(resolve=>{const tx=db.transaction('files','readonly'),req=tx.objectStore('files').getAll();req.onsuccess=()=>resolve(req.result||[])})}
async function loadFiles(cid){const list=$('fileList'),files=await getFiles(cid);if(!files.length){list.innerHTML='<div class="empty">No files yet. Upload lecture notes, assignments, reports or past-year papers here.</div>';return}list.innerHTML='';files.sort((a,b)=>b.created-a.created).forEach(f=>{const row=document.createElement('div');row.className='file-row';row.innerHTML=`<div><div class="file-title">${esc(f.name)}</div><div class="file-meta">${esc(f.category||'Other')} · ${formatBytes(f.size||0)} · ${new Date(f.created).toLocaleDateString()}</div></div><div class="actions"><button class="mini" data-open>Open</button><button class="mini" data-down>Save</button><button class="mini" data-del>Delete</button></div>`;row.querySelector('[data-open]').onclick=()=>openBlob(f);row.querySelector('[data-down]').onclick=()=>downloadBlob(f);row.querySelector('[data-del]').onclick=()=>deleteFile(f.id,cid);list.appendChild(row)})}
function openBlob(f){const url=URL.createObjectURL(f.blob);window.open(url,'_blank');setTimeout(()=>URL.revokeObjectURL(url),60000)}
function downloadBlob(f){const url=URL.createObjectURL(f.blob),a=document.createElement('a');a.href=url;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function deleteFile(id,cid){if(!confirm('Delete this file from the Study Hub?'))return;const tx=db.transaction('files','readwrite');tx.objectStore('files').delete(id);tx.oncomplete=()=>{loadFiles(cid);refreshCounts();refreshDashboard();renderFileCenter();toast('File deleted')}}
async function refreshCounts(){if(!db)return;const tasks=getTasks().filter(t=>!t.done);for(const s of allSemesters()){for(const c of s.courses){const id=courseId(s.id,c[0]),files=await getFiles(id);document.querySelectorAll('#count-'+cssSafe(id)).forEach(el=>el.textContent=files.length+' file'+(files.length===1?'':'s'));const n=tasks.filter(t=>t.courseId===id).length;document.querySelectorAll('#taskcount-'+cssSafe(id)).forEach(el=>el.textContent=n+' task'+(n===1?'':'s'))}}}
function countAllFiles(){return new Promise(resolve=>{const tx=db.transaction('files','readonly'),req=tx.objectStore('files').count();req.onsuccess=()=>resolve(req.result||0)})}
async function refreshDashboard(){const sems=allSemesters(),courses=sems.flatMap(s=>s.courses),credits=courses.reduce((a,c)=>a+Number(c[2]),0),tasks=getTasks();$('statCourses').textContent=courses.length;$('statCredits').textContent=credits;$('statTasks').textContent=tasks.filter(t=>!t.done).length;$('statFiles').textContent=db?await countAllFiles():0;renderUpcoming(tasks);renderRecentFiles();refreshStorage()}
function renderUpcoming(tasks){const list=$('upcomingTasks'),open=tasks.filter(t=>!t.done).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')).slice(0,6);if(!open.length){list.innerHTML='<div class="empty">No open tasks. Add tasks inside any course.</div>';return}list.innerHTML='';open.forEach(t=>{const d=document.createElement('div');d.className='deadline';d.innerHTML=`<div><b>${esc(t.title)}</b><small>${esc(t.courseCode)} · ${esc(t.courseName)}</small></div><div class="due">${t.due?formatDate(t.due):'No date'}</div>`;list.appendChild(d)})}
async function renderRecentFiles(){const box=$('recentFiles');if(!box||!db)return;const files=(await getAllFiles()).sort((a,b)=>b.created-a.created).slice(0,5);if(!files.length){box.innerHTML='<div class="empty"><strong>No files yet</strong>Open any course and upload your lecture notes, assignment or past-year paper.</div>';return}box.innerHTML='';files.forEach(f=>{const info=courseInfoFromId(f.courseId),r=document.createElement('div');r.className='recent-file';r.innerHTML=`<div><b>${esc(f.name)}</b><small>${esc(info.code)} · ${esc(f.category||'Other')} · ${formatBytes(f.size||0)}</small></div><button class="mini">Open</button>`;r.querySelector('button').onclick=()=>openBlob(f);box.appendChild(r)})}
async function renderFileCenter(){const list=$('globalFileList');if(!list||!db)return;const q=($('globalFileSearch')?.value||'').trim().toLowerCase(),sem=$('globalSemFilter')?.value||'',cat=$('globalCatFilter')?.value||'';let files=await getAllFiles();files=files.map(f=>({...f,_info:courseInfoFromId(f.courseId)})).filter(f=>{const hay=(f.name+' '+f._info.code+' '+f._info.name+' '+(f.category||'')).toLowerCase();return(!q||hay.includes(q))&&(!sem||f._info.sem===sem)&&(!cat||(f.category||'Other')===cat)}).sort((a,b)=>b.created-a.created);$('fileCenterCount').textContent=files.length+' file'+(files.length===1?'':'s');if(!files.length){list.innerHTML='<div class="empty"><strong>No matching files</strong>Try another filter, or open a course to upload files.</div>';return}list.innerHTML='';files.forEach(f=>{const r=document.createElement('div');r.className='global-file';r.innerHTML=`<div class="global-file-main"><div class="global-file-name">${esc(f.name)}</div><div class="global-file-sub"><span class="tag">${esc(f._info.sem)}</span><span class="tag">${esc(f._info.code)}</span><span class="tag">${esc(f.category||'Other')}</span><span>${formatBytes(f.size||0)}</span><span>${new Date(f.created).toLocaleDateString()}</span></div></div><div class="actions"><button class="mini" data-course>Course</button><button class="mini" data-open>Open</button><button class="mini" data-down>Save</button><button class="mini" data-del>Delete</button></div>`;r.querySelector('[data-course]').onclick=()=>openCourse(f._info);r.querySelector('[data-open]').onclick=()=>openBlob(f);r.querySelector('[data-down]').onclick=()=>downloadBlob(f);r.querySelector('[data-del]').onclick=()=>deleteFile(f.id,f.courseId);list.appendChild(r)})}
['globalFileSearch','globalSemFilter','globalCatFilter'].forEach(id=>{setTimeout(()=>{const el=$(id);if(el)el.addEventListener(id==='globalFileSearch'?'input':'change',renderFileCenter)},0)});
async function refreshStorage(){if(!navigator.storage?.estimate)return $('storageInfo').textContent='Storage estimate not supported by this browser.';const e=await navigator.storage.estimate(),used=e.usage||0,quota=e.quota||0,pct=quota?Math.min(100,used/quota*100):0;$('storageInfo').textContent=`${formatBytes(used)} used of approximately ${formatBytes(quota)} available`;$('storageBar').style.width=pct+'%'}
function formatBytes(n){if(!n)return'0 B';const units=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<units.length-1){n/=1024;i++}return n.toFixed(i?1:0)+' '+units[i]}
const dz=$('dropzone'),fi=$('fileInput');fi.addEventListener('change',e=>{addFiles(e.target.files);fi.value=''});['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>addFiles(e.dataTransfer.files));
function toggleTheme(){const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'light':'dark';localStorage.setItem(themeKey,dark?'light':'dark');updateThemeBtn()}
function updateThemeBtn(){$('themeBtn').textContent=document.documentElement.dataset.theme==='dark'?'☀️':'🌙'}
function blobToBase64(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob)})}
async function exportBackup(){if(!db)return;toast('Preparing backup...');const files=await getAllFiles(),packed=[];for(const f of files){packed.push({...f,blob:await blobToBase64(f.blob)})}const data={version:3,exportedAt:new Date().toISOString(),local:{custom:localStorage.getItem(customKey)||'[]',notes:localStorage.getItem(notesKey)||'{}',tasks:localStorage.getItem(tasksKey)||'[]'},files:packed};const blob=new Blob([JSON.stringify(data)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='UTAR_Study_Hub_Backup_'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Backup downloaded ✓')}
$('restoreInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!confirm('Restore this backup? Existing notes/tasks/files may be replaced or duplicated.'))return;if(data.local){localStorage.setItem(customKey,data.local.custom||'[]');localStorage.setItem(notesKey,data.local.notes||'{}');localStorage.setItem(tasksKey,data.local.tasks||'[]')}if(data.files?.length){const decoded=[];for(const f of data.files){const res=await fetch(f.blob),blob=await res.blob();const copy={...f,blob};delete copy.id;decoded.push(copy)}const tx=db.transaction('files','readwrite'),store=tx.objectStore('files');store.clear();decoded.forEach(copy=>store.add(copy));await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}renderCourses();renderFileCenter();toast('Backup restored ✓')}catch(err){alert('Could not restore this backup file.')}e.target.value=''});
const savedTheme=localStorage.getItem(themeKey)||'light';document.documentElement.dataset.theme=savedTheme;updateThemeBtn();
initDB().then(renderCourses).catch(()=>{renderCourses();alert('Browser local file storage is blocked. Try Chrome or Edge.')});